<a href="https://colab.research.google.com/github/yamuna009/advanced-python-working-with-data-4312001/blob/main/Advancenumphymethod.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [4]:
L4 = []
L2 =[1,2,3]
for e in L2:
  L4.append(e**2)
print(L4)

[1, 4, 9]


In [6]:
arr =np.array([1,2,3,4]) # all below are possible with arrays and not with list
print(arr**2)

[ 1  4  9 16]


In [7]:
np.sqrt(arr)

array([1.        , 1.41421356, 1.73205081, 2.        ])

In [8]:
np.log(arr)

array([0.        , 0.69314718, 1.09861229, 1.38629436])

In [9]:
np.exp(arr)

array([ 2.71828183,  7.3890561 , 20.08553692, 54.59815003])

In [10]:
np.tanh(arr)

array([0.76159416, 0.96402758, 0.99505475, 0.9993293 ])

In [12]:
#The Dot Product, is some kind of inner product in numphy
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])

In [13]:
dot =0
for e,f in zip(a,b):
  dot +=e*f
dot

70

In [14]:
dot =0
for i in range(len(a)):
  dot += a[i] *b[i]
dot

70

In [15]:
a*b

array([ 5, 12, 21, 32])

In [16]:
np.sum(a*b)

70

In [17]:
(a*b).sum() # we can this methods with numpy arrays as well

70

In [18]:
np.dot(a,b)

70

In [20]:
a.dot(b)

70

In [21]:
a@b #this symbol does dot functionality.

70

In [22]:
amag =np.sqrt((a*a).sum())

In [23]:
amag

5.477225575051661

In [ ]:
#class numpy.matrix(....) this is not recommonded to use

In [24]:
L= [[1,2],[3,4]]
L

[[1, 2], [3, 4]]

In [25]:
L[0]

[1, 2]

In [26]:
L[0][1]

2

In [27]:
A =np.array([[1,2],[3,4]])
A

array([[1, 2],
       [3, 4]])

In [28]:
A[0][1]

2

In [29]:
A[0,1]

2

In [30]:
A[:,0]

array([1, 3])

In [31]:
A.T   # this is not possible with List

array([[1, 3],
       [2, 4]])

In [32]:
np.exp(A)  #with array

array([[ 2.71828183,  7.3890561 ],
       [20.08553692, 54.59815003]])

In [33]:
np.exp(L) #with list coverted to array but

array([[ 2.71828183,  7.3890561 ],
       [20.08553692, 54.59815003]])

In [34]:
#matric multiplication
B =np.array([[1,2,3],[4,5,6]])

In [35]:
A.dot(B) #here we can't use A * B,because * does simple element wise mulitplication
# and not  matrix multiplication, so in this case we need to use only dot

array([[ 9, 12, 15],
       [19, 26, 33]])

In [36]:
A.dot(B.T)

ValueError: shapes (2,2) and (3,2) not aligned: 2 (dim 1) != 3 (dim 0)

--------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-36-80d79729e8e6> in <cell line: 1>()
----> 1 A.dot(B.T)

ValueError: shapes (2,2) and (3,2) not aligned: 2 (dim 1) != 3 (dim 0)

In [37]:
np.trace(A)

5

In [39]:
np.diag(A)

array([1, 4])

In [40]:
np.diag([1,4])

array([[1, 0],
       [0, 4]])

In [ ]:
#Generate Data ,
# what if we wanted to generate data from 100 and 1000 of dimensions
#in Nueral network and clustring algorothm we generate synthetic or random data
#to test the algorithm and data pripelines as well.

In [41]:
np.zeros((2,3)) #we initialize or generate zeros with tuple

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
np.ones((2,3))      # if we want to initalize with 1's

In [42]:
10*np.ones((2,3)) # if we want to initalize with 10 ,
# we give any value any thing mulitplied 1 gives the number itself.

array([[10., 10., 10.],
       [10., 10., 10.]])

In [43]:
np.eye(3)    # to create identity matrics

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [44]:
np.random.random()     # how to generate array with random numbers

0.5553097101560479

In [45]:
np.random.random((2,3))

array([[0.50772565, 0.07684348, 0.35355823],
       [0.54394663, 0.01087381, 0.86366133]])

In [46]:
np.random.randn(2,3)

array([[-0.53724508, -1.00839708,  0.24414893],
       [-0.05531735, -0.4055564 , -0.65287198]])

In [47]:
R= np.random.randn(10000)

In [48]:
R.mean() # calculating mean value

-0.001238072400734515

In [49]:
np.mean(R)

-0.001238072400734515

In [50]:
R.var() #calculating varience

0.9962364033327727

In [ ]:
R.std() #square root of varience

In [52]:
R= np.random.randn(10000,3)

In [53]:
R.mean(axis=0)

array([-0.01101729, -0.01227072, -0.01977847])

In [55]:
R.mean(axis=1).shape

(10000,)